// Central Ionicons name registry for every non-emotion icon in the app
// (emotion icons live alongside their data in src/data/emotions.js).
// Keeping names here means no screen ever hardcodes an icon string.
export const ICONS = {
  BRAND: 'compass-outline',
  ONBOARDING_WELCOME: 'compass-outline',
  ONBOARDING_CONVERSATION: 'chatbubbles-outline',
  ONBOARDING_PROGRESS: 'trending-up-outline',
  ONBOARDING_SUPPORT: 'leaf-outline',
  LOGIN: 'lock-closed-outline',
  REGISTER: 'person-add-outline',
  CONVERSATION: 'chatbubble-ellipses-outline',
  RATING: 'options-outline',
  CELEBRATION: 'trophy-outline',
  ROADMAP: 'map-outline',
  COMPLETE: 'checkmark-circle-outline',
  HOME: 'home-outline',
  CHART: 'bar-chart-outline',
  TREND: 'trending-up-outline',
  CHECK_IN: 'calendar-outline',
  HISTORY: 'time-outline',
  PROFILE: 'person-outline',
  EDIT: 'create-outline',
  SETTINGS: 'settings-outline',
  NOTIFICATIONS: 'notifications-outline',
  LANGUAGE: 'globe-outline',
  VOICE: 'mic-outline',
  ABOUT: 'information-circle-outline',
  HELP: 'help-circle-outline',
  ERROR: 'alert-circle-outline',
  EMPTY: 'cloud-outline',
  PLAY: 'play',
  PAUSE: 'pause',
  SEND: 'send',
  BACK: 'arrow-back',
  CLOSE: 'close',
  LOGOUT: 'log-out-outline',
  CHEVRON_RIGHT: 'chevron-forward',
};
